### ISSUE TITLE
Problems build on Windows

### ISSUE THREAD

**Issue by nathan666** [schdub/adbgui#1]
Hey Oleg,

thanks for sharing this.
I have tried to compile it via QT on Windows but i get this error:

C:\Users\damar1st\Downloads\adbgui-master\adb.h:15: Fehler: C1017: invalid integer constant expression

Thanks for this great stuff !!!!

**Comment by schdub** [comment]
@nathan666, thanks.

https://github.com/schdub/adbgui/commit/a7b8be40f29662504abbb17319f0af98745344bf should fix this issuse.

PS: remember that path to adb.exe tool SHOULD BE in PATH environment variable.
https://stackoverflow.com/questions/20564514/adb-is-not-recognized-as-an-internal-or-external-command-operable-program-or
